export const persons = [
      { 
        id: 1,
        name: 'Alice', 
        occupation: 'Engineer', 
        salary: 2800, 
        phone: '0401232323', 
        email: 'alice@email.com', 
        pet: 'Dog', 
        startDate: "2015-02-02",
        location: "Helsinki",
        department: "Heavy industry",
        skills: ["Mathematical ability", "Logical thinking", "Scientific acumen"]
    },
    { 
        id: 2,
        name: 'Bob', 
        occupation: 'Designer', 
        salary: 3400, 
        phone: '0410899827', 
        email: 'bob@email.com', 
        pet: 'Cat',
        startDate: "2017-06-05",
        location: "New York",
        department: "Design",
        skills: ["Creativity", "Design principles", "Typography"]
    },
    { 
        id: 3,
        name: 'Charlie', 
        occupation: 'Teacher', 
        salary: 4100, 
        phone: '0403879655', 
        email: 'charlie@email.com', 
        pet: 'Fish',
        startDate: "2011-03-04",
        location: "Ottava",
        department: "Education",
        skills: ["Conflict resolution", "Communication", "Critical thinking"]
    },
    { 
        id: 4,
        name: 'Diana', 
        occupation: 'Doctor', 
        salary: 3000, 
        phone: '0409887234', 
        email: 'diana@email.com', 
        pet: 'Eagle',
        startDate: "2023-02-11",
        location: "Paris",
        department: "Healthcare",
        skills: ["Patient care", "Clinical knowladge", "Symptomatology"]
    },
    { 
        id: 5,
        name: 'Lisa', 
        occupation: 'Jornalist', 
        salary: 2900, 
        phone: '0414495676', 
        email: 'lisa@email.com', 
        pet: 'Fox', 
        startDate: "2009-02-10",
        location: "Dubai",
        department: "Press",
        skills: ["Media production", "Communication", "Stress resistance"]
    },
    { 
        id: 6,
        name: 'John', 
        occupation: 'Software developer', 
        salary: 5900, 
        phone: '0403557423', 
        email: 'john@email.com', 
        pet: 'Dinosaur',
        startDate: "2020-08-06",
        location: "Sydney",
        department: "IT",
        skills: ["Programming", "Problem solving", "Cloud computing"]
    },
    { 
        id: 7,
        name: 'Lara', 
        occupation: 'Police officer', 
        salary: 3600, 
        phone: '0403771122', 
        email: 'lara@email.com', 
        pet: 'Horse',
        startDate: "2023-09-09",
        location: "Lisbon",
        department: "Law enforcement",
        skills: ["Firearms", "Communication", "Crisis management"]
    },
    { 
        id: 8,
        name: 'Timo', 
        occupation: 'Hairdresser', 
        salary: 1900, 
        phone: '0528763561', 
        email: 'timo@email.com', 
        pet: 'Snake',
        startDate: "2019-03-12",
        location: "Kyiv",
        department: "Beauty",
        skills: ["Customer service", "Communication", "Flexibility"]
    },
    { 
        id: 9,
        name: 'Lea', 
        occupation: 'Sales manager', 
        salary: 2400, 
        phone: '0528844561', 
        email: 'lea@email.com', 
        pet: 'Squirrel',
        startDate: "2015-01-05",
        location: "Stockholm",
        department: "Sales",
        skills: ["Customer service", "Communication", "Business management"]
    },
    { 
        id: 10,
        name: 'Eleonor', 
        occupation: 'HR manager', 
        salary: 3700, 
        phone: '0401133344', 
        email: 'eleonor@email.com', 
        pet: 'Alligator',
        startDate: "2024-10-20",
        location: "Copenhagen",
        department: "Human Resources",
        skills: ["Recruiting", "Communication", "Employee Relations"]
    }
    ];